nameOverride: ""

global:
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent
  # storageClass: myStorageClass

webapp:
  image:
    repository: blotout/airbyte-webapp
    tag: 0.13.1
  replicas: 1
  service:
    name: airbyte-webapp-svc
    containerPort: 80

server:
  image:
    repository: blotout/airbyte-server
    tag: 0.13.1

scheduler:
  image:
    repository: blotout/airbyte-scheduler
    tag: 0.13.1

seed:
  image:
    repository: blotout/airbyte-seed
    tag: 0.13.1

temporal:
  image:
    repository: temporalio/auto-setup
    tag: 1.7.0
  replicas: 1

# volumeconfigs:
#   disksize: "5"
# volumeworkspace:
#   disksize: "5"

ingress:
  enabled: "true"
  annotations: {}
  labels: {}
  hosts:
    - airbyte.example.com
  paths:
    - /
