apiVersion: v2

version: "0.13.1"

appVersion: 0.1.0

name: complii-backend

description: A Helm chart for complii

keywords:
- complii-backend

maintainers:
- name: satish
- name: ojasvi

type: application
