apiVersion: v1
appVersion: 0.1.1
description: A Helm chart for App, a declarative, GitOps continuous delivery helm chart for Kubernetes.
keywords:
- shopgpt-backend
name: shopgpt-backend
version: "v0.1.3"
