
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Connectorbuilder Configuration
*/}}

{{/*
Renders the connectorBuilderServer.aiAssistUrlBase value
*/}}
{{- define "airbyte.connectorBuilder.aiAssistUrlBase" }}
    {{- .Values.connectorBuilderServer.aiAssistUrlBase }}
{{- end }}

{{/*
Renders the connectorBuilder.aiAssistUrlBase environment variable
*/}}
{{- define "airbyte.connectorBuilder.aiAssistUrlBase.env" }}
- name: AI_ASSIST_URL_BASE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: AI_ASSIST_URL_BASE
{{- end }}

{{/*
Renders the connectorBuilder.manifestServerApi.basePath value (URL of connector-builder-server for ManifestServerApiClient).
Required by server: airbyte.manifest-server-api.base-path must match pattern .+
*/}}
{{- define "airbyte.connectorBuilder.manifestServerApi.basePath" }}
    {{- .Values.connectorBuilderServer.manifestServerApi.basePath | default (include "airbyte.common.connectorBuilderServer.apiHost" .) }}
{{- end }}

{{/*
Renders the connectorBuilder.manifestServerApi.basePath environment variable.
use literal value (same as CONNECTOR_BUILDER_SERVER_API_HOST) so server always has non-empty base-path.
*/}}
{{- define "airbyte.connectorBuilder.manifestServerApi.basePath.env" }}
- name: AIRBYTE_MANIFEST_SERVER_API_BASE_PATH
  value: {{ include "airbyte.connectorBuilder.manifestServerApi.basePath" . | quote }}
{{- end }}

{{/*
Renders the set of all connectorBuilder environment variables
*/}}
{{- define "airbyte.connectorBuilder.envs" }}
{{- include "airbyte.connectorBuilder.aiAssistUrlBase.env" . }}
{{- include "airbyte.connectorBuilder.manifestServerApi.basePath.env" . }}
{{- end }}

{{/*
Renders the set of all connectorBuilder config map variables
*/}}
{{- define "airbyte.connectorBuilder.configVars" }}
AI_ASSIST_URL_BASE: {{ include "airbyte.connectorBuilder.aiAssistUrlBase" . | quote }}
AIRBYTE_MANIFEST_SERVER_API_BASE_PATH: {{ include "airbyte.connectorBuilder.manifestServerApi.basePath" . | quote }}
{{- end }}
