
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Webapp Configuration
*/}}

{{/*
Renders the webapp.api.url value
*/}}
{{- define "airbyte.webapp.api.url" }}
    {{- "/api/v1" }}
{{- end }}

{{/*
Renders the webapp.api.url environment variable
*/}}
{{- define "airbyte.webapp.api.url.env" }}
- name: API_URL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: API_URL
{{- end }}

{{/*
Renders the webapp connector-builder API value: path (e.g. /connector-builder-api) when webapp.connectorBuilderServer.url is set, otherwise internal service host for in-cluster access.
*/}}
{{- define "airbyte.webapp.connectorBuilderServer.host" }}
    {{- if and .Values.webapp.connectorBuilderServer .Values.webapp.connectorBuilderServer.url }}
    {{- .Values.webapp.connectorBuilderServer.url | trimSuffix "/" }}
    {{- else }}
    {{- (printf "%s-airbyte-connector-builder-server-svc.%s:%d" .Release.Name .Release.Namespace (int .Values.connectorBuilderServer.service.port)) }}
    {{- end }}
{{- end }}

{{/*
Renders the webapp.connectorBuilderServer.host environment variable
*/}}
{{- define "airbyte.webapp.connectorBuilderServer.host.env" }}
- name: CONNECTOR_BUILDER_API_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONNECTOR_BUILDER_API_HOST
{{- end }}

{{/*
Renders the set of all webapp environment variables
*/}}
{{- define "airbyte.webapp.envs" }}
{{- include "airbyte.webapp.api.url.env" . }}
{{- include "airbyte.webapp.connectorBuilderServer.host.env" . }}
{{- end }}

{{/*
Renders the set of all webapp config map variables
*/}}
{{- define "airbyte.webapp.configVars" }}
API_URL: {{ include "airbyte.webapp.api.url" . | quote }}
CONNECTOR_BUILDER_API_HOST: {{ include "airbyte.webapp.connectorBuilderServer.host" . | quote }}
{{- end }}
