
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Workloadlauncher Configuration
*/}}

{{/*
Override with workloadLauncher.controlPlane.tokenEndpoint in values if needed.
*/}}
{{- define "airbyte.workloadLauncher.controlPlane.tokenEndpoint" }}
    {{- $internalBase := printf "http://%s-airbyte-server-svc.%s:%d" .Release.Name .Release.Namespace (int .Values.server.service.port) }}
    {{- $internalUrl := printf "%s/api/v1/dataplanes/token" $internalBase }}
    {{- $publicUrl := printf "%s/api/v1/dataplanes/token" (include "airbyte.common.airbyteUrl" .) }}
    {{- $clusterType := include "airbyte.common.cluster.type" . }}
    {{- $useInternal := and (ne $clusterType "data-plane") (ne .Values.workloadLauncher.controlPlane.useInternalUrl false) }}
    {{- if .Values.workloadLauncher.controlPlane.tokenEndpoint }}
    {{- $base := .Values.workloadLauncher.controlPlane.tokenEndpoint | trimSuffix "/" }}
    {{- if hasSuffix "/api/v1/dataplanes/token" $base }}{{- $base }}{{- else }}{{- printf "%s/api/v1/dataplanes/token" $base }}{{- end }}
    {{- else if $useInternal }}
    {{- $internalUrl }}
    {{- else }}
    {{- $publicUrl }}
    {{- end }}
{{- end }}

{{/*
Renders the workloadLauncher.controlPlane.tokenEndpoint environment variable
*/}}
{{- define "airbyte.workloadLauncher.controlPlane.tokenEndpoint.env" }}
- name: CONTROL_PLANE_TOKEN_ENDPOINT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONTROL_PLANE_TOKEN_ENDPOINT
{{- end }}

{{/*
Renders the workloadLauncher.enabled value
*/}}
{{- define "airbyte.workloadLauncher.enabled" }}
	{{- if eq .Values.workloadLauncher.enabled nil }}
    	{{- true }}
	{{- else }}
    	{{- .Values.workloadLauncher.enabled }}
	{{- end }}
{{- end }}

{{/*
Renders the workloadLauncher.enabled environment variable
*/}}
{{- define "airbyte.workloadLauncher.enabled.env" }}
- name: WORKLOAD_LAUNCHER_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: WORKLOAD_LAUNCHER_ENABLED
{{- end }}

{{/*
Renders the workloadLauncher.parallelism value
*/}}
{{- define "airbyte.workloadLauncher.parallelism" }}
    {{- .Values.workloadLauncher.parallelism | default 10 }}
{{- end }}

{{/*
Renders the workloadLauncher.parallelism environment variable
*/}}
{{- define "airbyte.workloadLauncher.parallelism.env" }}
- name: WORKLOAD_LAUNCHER_PARALLELISM
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: WORKLOAD_LAUNCHER_PARALLELISM
{{- end }}

{{/*
Renders the set of all workloadLauncher environment variables
*/}}
{{- define "airbyte.workloadLauncher.envs" }}
{{- include "airbyte.workloadLauncher.controlPlane.tokenEndpoint.env" . }}
{{- include "airbyte.workloadLauncher.enabled.env" . }}
{{- include "airbyte.workloadLauncher.parallelism.env" . }}
{{- end }}

{{/*
Renders the set of all workloadLauncher config map variables
*/}}
{{- define "airbyte.workloadLauncher.configVars" }}
CONTROL_PLANE_TOKEN_ENDPOINT: {{ include "airbyte.workloadLauncher.controlPlane.tokenEndpoint" . | quote }}
WORKLOAD_LAUNCHER_ENABLED: {{ include "airbyte.workloadLauncher.enabled" . | quote }}
WORKLOAD_LAUNCHER_PARALLELISM: {{ include "airbyte.workloadLauncher.parallelism" . | quote }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane secret name (where to read DATAPLANE_CLIENT_ID/SECRET).
When existingSecretName is set, use it so credentials come from that secret (no hardcoding in values).
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.secretName" }}
{{- if .Values.workloadLauncher.dataPlane.existingSecretName }}
    {{- .Values.workloadLauncher.dataPlane.existingSecretName }}
{{- else if .Values.workloadLauncher.dataPlane.secretName }}
    {{- .Values.workloadLauncher.dataPlane.secretName }}
{{- else }}
    {{- .Values.global.secretName | default (printf "%s-airbyte-secrets" .Release.Name) }}
{{- end }}
{{- end }}

{{/*
True when dataplane credentials are read from an existing secret (don't write them into the chart secret).
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.useExistingSecret" }}
    {{- .Values.workloadLauncher.dataPlane.existingSecretName }}
{{- end }}

{{/*
Release-unique default dataplane clientId (stable across upgrades).
Server DataplaneTokenServiceDataImpl expects a valid UUID; format 32 hex chars as 8-4-4-4-12.
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientId.default" }}
    {{- $h := (printf "id-%s" (include "airbyte.secretSeed.hashBase" .) | sha256sum | nospace | trunc 32) }}
    {{- $p1 := trunc 8 $h }}{{ $r1 := trimPrefix $p1 $h }}{{ $p2 := trunc 4 $r1 }}{{ $r2 := trimPrefix $p2 $r1 }}{{ $p3 := trunc 4 $r2 }}{{ $r3 := trimPrefix $p3 $r2 }}{{ $p4 := trunc 4 $r3 }}{{ $r4 := trimPrefix $p4 $r3 }}{{ $p5 := trunc 12 $r4 }}
    {{- $p1 }}-{{ $p2 }}-{{ $p3 }}-{{ $p4 }}-{{ $p5 }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientId value.
Use or so empty string is treated as unset and default (UUID) is used; set explicitly to match service_accounts.id in DB.
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientId" }}
    {{- or .Values.workloadLauncher.dataPlane.clientId (include "airbyte.workloadLauncher.dataPlane.clientId.default" .) }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientId secret key.
Default "dataplane-client-id" so server/launcher read the key that matches service_accounts in DB (secret may also have DATAPLANE_CLIENT_ID).
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientId.secretKey" }}
	{{- .Values.workloadLauncher.dataPlane.clientIdSecretKey | default "dataplane-client-id" }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientId environment variable
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientId.env" }}
- name: DATAPLANE_CLIENT_ID
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte.workloadLauncher.dataPlane.secretName" . }}
      key: {{ include "airbyte.workloadLauncher.dataPlane.clientId.secretKey" . }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientIdSecretName value (secret that holds DATAPLANE_CLIENT_ID).
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientIdSecretName" }}
    {{- .Values.workloadLauncher.dataPlane.clientIdSecretName | default (include "airbyte.workloadLauncher.dataPlane.secretName" .) }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientIdSecretName environment variable
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientIdSecretName.env" }}
- name: DATAPLANE_CLIENT_ID_SECRET_NAME
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: DATAPLANE_CLIENT_ID_SECRET_NAME
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientIdSecretKey value
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientIdSecretKey" }}
    {{- .Values.workloadLauncher.dataPlane.clientIdSecretKey | default (include "airbyte.workloadLauncher.dataPlane.clientId.secretKey" .) }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientIdSecretKey environment variable
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientIdSecretKey.env" }}
- name: DATAPLANE_CLIENT_ID_SECRET_KEY
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: DATAPLANE_CLIENT_ID_SECRET_KEY
{{- end }}

{{/*
Release-unique default dataplane clientSecret (stable across upgrades).
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientSecret.default" }}
    {{- printf "dataplane-%s" (printf "secret-%s" (include "airbyte.secretSeed.hashBase" .) | sha256sum | trunc 32) }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientSecret value.
Use or so empty string is treated as unset; set explicitly to match the secret for the service account in DB.
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientSecret" }}
    {{- or .Values.workloadLauncher.dataPlane.clientSecret (include "airbyte.workloadLauncher.dataPlane.clientSecret.default" .) }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientSecret secret key
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientSecret.secretKey" }}
	{{- .Values.workloadLauncher.dataPlane.clientSecretSecretKey | default "dataplane-client-secret" }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientSecret environment variable
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientSecret.env" }}
- name: DATAPLANE_CLIENT_SECRET
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte.workloadLauncher.dataPlane.secretName" . }}
      key: {{ include "airbyte.workloadLauncher.dataPlane.clientSecret.secretKey" . }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientSecretSecretName value (secret that holds DATAPLANE_CLIENT_SECRET).
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientSecretSecretName" }}
    {{- .Values.workloadLauncher.dataPlane.clientSecretSecretName | default (include "airbyte.workloadLauncher.dataPlane.secretName" .) }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientSecretSecretName environment variable
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientSecretSecretName.env" }}
- name: DATAPLANE_CLIENT_SECRET_SECRET_NAME
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: DATAPLANE_CLIENT_SECRET_SECRET_NAME
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientSecretSecretKey value
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientSecretSecretKey" }}
    {{- .Values.workloadLauncher.dataPlane.clientSecretSecretKey | default (include "airbyte.workloadLauncher.dataPlane.clientSecret.secretKey" .) }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientSecretSecretKey environment variable
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientSecretSecretKey.env" }}
- name: DATAPLANE_CLIENT_SECRET_SECRET_KEY
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: DATAPLANE_CLIENT_SECRET_SECRET_KEY
{{- end }}

{{/*
Renders the set of all workloadLauncher.dataPlane environment variables
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.envs" }}
{{- include "airbyte.workloadLauncher.dataPlane.clientId.env" . }}
{{- include "airbyte.workloadLauncher.dataPlane.clientIdSecretName.env" . }}
{{- include "airbyte.workloadLauncher.dataPlane.clientIdSecretKey.env" . }}
{{- include "airbyte.workloadLauncher.dataPlane.clientSecret.env" . }}
{{- include "airbyte.workloadLauncher.dataPlane.clientSecretSecretName.env" . }}
{{- include "airbyte.workloadLauncher.dataPlane.clientSecretSecretKey.env" . }}
{{- end }}

{{/*
Renders the set of all workloadLauncher.dataPlane config map variables
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.configVars" }}
DATAPLANE_CLIENT_ID_SECRET_NAME: {{ include "airbyte.workloadLauncher.dataPlane.clientIdSecretName" . | quote }}
DATAPLANE_CLIENT_ID_SECRET_KEY: {{ include "airbyte.workloadLauncher.dataPlane.clientIdSecretKey" . | quote }}
DATAPLANE_CLIENT_SECRET_SECRET_NAME: {{ include "airbyte.workloadLauncher.dataPlane.clientSecretSecretName" . | quote }}
DATAPLANE_CLIENT_SECRET_SECRET_KEY: {{ include "airbyte.workloadLauncher.dataPlane.clientSecretSecretKey" . | quote }}
{{- end }}

{{/*
Renders the set of all workloadLauncher.dataPlane secret variables.
- dataplane-client-id / dataplane-client-secret: secret keys used by default for secretKeyRef (server/launcher read these keys; matches Airbyte server token endpoint / service_accounts).
- DATAPLANE_CLIENT_ID / DATAPLANE_CLIENT_SECRET: same values under env-style keys so existing secrets or tools that use these key names also work.
Pods get env vars named DATAPLANE_CLIENT_ID and DATAPLANE_CLIENT_SECRET; the value is read from the secret key (default: dataplane-client-id / dataplane-client-secret).
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.secrets" }}
DATAPLANE_CLIENT_ID: {{ include "airbyte.workloadLauncher.dataPlane.clientId" . | quote }}
DATAPLANE_CLIENT_SECRET: {{ include "airbyte.workloadLauncher.dataPlane.clientSecret" . | quote }}
dataplane-client-id: {{ include "airbyte.workloadLauncher.dataPlane.clientId" . | quote }}
dataplane-client-secret: {{ include "airbyte.workloadLauncher.dataPlane.clientSecret" . | quote }}
{{- end }}

{{/*
Renders the workloadLauncher.connectorProfiler.image value
*/}}
{{- define "airbyte.workloadLauncher.images.connectorProfiler.image" }}
    {{- include "imageUrl" (list .Values.workloadLauncher.connectorProfiler.image $) }}
{{- end }}

{{/*
Renders the workloadLauncher.images.connectorProfiler.image environment variable
*/}}
{{- define "airbyte.workloadLauncher.images.connectorProfiler.image.env" }}
- name: CONNECTOR_PROFILER_IMAGE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONNECTOR_PROFILER_IMAGE
{{- end }}

{{/*
Renders the workloadLauncher.connectorSidecar.image value
*/}}
{{- define "airbyte.workloadLauncher.images.connectorSidecar.image" }}
    {{- include "imageUrl" (list .Values.workloadLauncher.connectorSidecar.image $) }}
{{- end }}

{{/*
Renders the workloadLauncher.images.connectorSidecar.image environment variable
*/}}
{{- define "airbyte.workloadLauncher.images.connectorSidecar.image.env" }}
- name: CONNECTOR_SIDECAR_IMAGE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONNECTOR_SIDECAR_IMAGE
{{- end }}

{{/*
Renders the workloadLauncher.containerOrchestrator.enabled value
*/}}
{{- define "airbyte.workloadLauncher.images.containerOrchestrator.enabled" }}
    {{- .Values.workloadLauncher.containerOrchestrator.enabled }}
{{- end }}

{{/*
Renders the workloadLauncher.images.containerOrchestrator.enabled environment variable
*/}}
{{- define "airbyte.workloadLauncher.images.containerOrchestrator.enabled.env" }}
- name: CONTAINER_ORCHESTRATOR_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONTAINER_ORCHESTRATOR_ENABLED
{{- end }}

{{/*
Renders the workloadLauncher.containerOrchestrator.image value
*/}}
{{- define "airbyte.workloadLauncher.images.containerOrchestrator.image" }}
    {{- include "imageUrl" (list .Values.workloadLauncher.containerOrchestrator.image $) }}
{{- end }}

{{/*
Renders the workloadLauncher.images.containerOrchestrator.image environment variable
*/}}
{{- define "airbyte.workloadLauncher.images.containerOrchestrator.image.env" }}
- name: CONTAINER_ORCHESTRATOR_IMAGE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONTAINER_ORCHESTRATOR_IMAGE
{{- end }}

{{/*
Renders the workloadLauncher.workloadInit.image value
*/}}
{{- define "airbyte.workloadLauncher.images.workloadInit.image" }}
    {{- include "imageUrl" (list .Values.workloadLauncher.workloadInit.image $) }}
{{- end }}

{{/*
Renders the workloadLauncher.images.workloadInit.image environment variable
*/}}
{{- define "airbyte.workloadLauncher.images.workloadInit.image.env" }}
- name: WORKLOAD_INIT_IMAGE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: WORKLOAD_INIT_IMAGE
{{- end }}

{{/*
Renders the set of all workloadLauncher.images environment variables
*/}}
{{- define "airbyte.workloadLauncher.images.envs" }}
{{- include "airbyte.workloadLauncher.images.connectorProfiler.image.env" . }}
{{- include "airbyte.workloadLauncher.images.connectorSidecar.image.env" . }}
{{- include "airbyte.workloadLauncher.images.containerOrchestrator.enabled.env" . }}
{{- include "airbyte.workloadLauncher.images.containerOrchestrator.image.env" . }}
{{- include "airbyte.workloadLauncher.images.workloadInit.image.env" . }}
{{- end }}

{{/*
Renders the set of all workloadLauncher.images config map variables
*/}}
{{- define "airbyte.workloadLauncher.images.configVars" }}
CONNECTOR_PROFILER_IMAGE: {{ include "airbyte.workloadLauncher.images.connectorProfiler.image" . | quote }}
CONNECTOR_SIDECAR_IMAGE: {{ include "airbyte.workloadLauncher.images.connectorSidecar.image" . | quote }}
CONTAINER_ORCHESTRATOR_ENABLED: {{ include "airbyte.workloadLauncher.images.containerOrchestrator.enabled" . | quote }}
CONTAINER_ORCHESTRATOR_IMAGE: {{ include "airbyte.workloadLauncher.images.containerOrchestrator.image" . | quote }}
WORKLOAD_INIT_IMAGE: {{ include "airbyte.workloadLauncher.images.workloadInit.image" . | quote }}
{{- end }}
