apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}-{{ .Release.Name }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: application
    app.kubernetes.io/component: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}-{{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.name" . }}-{{ .Release.Name }}
        helm.sh/chart: {{ include "app.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/part-of: application
        app.kubernetes.io/component: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.image.tag | quote }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext }}
      securityContext: {{- toYaml .Values.image.securityContext | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: {{ .Release.Name }}
        env:
        {{- range $conf, $value := .Values.env }}
          - name: {{ $conf | quote }}
            value: {{ $value | quote }}
        {{- end }}
          - name: SMTP_HOST
            valueFrom:
              configMapKeyRef:
                name: special-config
                key: AIRFLOW__SMTP__SMTP_HOST
          - name: SMTP_USER
            valueFrom:
              configMapKeyRef:
                name: special-config
                key: AIRFLOW__SMTP__SMTP_USER
          - name: SMTP_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: special-config
                key: AIRFLOW__SMTP__SMTP_PASSWORD
          - name: SMTP_PORT
            valueFrom:
              configMapKeyRef:
                name: special-config
                key: AIRFLOW__SMTP__SMTP_PORT
          - name: SMTP_SSL
            valueFrom:
              configMapKeyRef:
                name: special-config
                key: AIRFLOW__SMTP__SMTP_SSL
          - name: SMTP_MAIL_FROM
            valueFrom:
              configMapKeyRef:
                name: special-config
                key: AIRFLOW__SMTP__SMTP_MAIL_FROM
          - name: ORGANIZATION_NAME
            valueFrom:
              configMapKeyRef:
                name: special-config
                key: ORGANIZATION_NAME
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: special-config
                key: ENVIRONMENT
          - name: AIRFLOW_DAG_FAILED_EMAIL
            valueFrom:
              configMapKeyRef:
                name: special-config
                key: AIRFLOW_DAG_FAILED_EMAIL
        {{- if .Values.containerSecurityContext }}
        securityContext: {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        {{- end }}
        resources:
{{- toYaml .Values.resources | nindent 10 }}
        terminationMessagePath: /dev/termination-log
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
