apiVersion: v1
kind: ConfigMap
metadata:
  name: sweep-pod-script
data:
  sweep-pod.sh: |
    #!/bin/bash

    get_worker_pods () {
      kubectl -n ${KUBE_NAMESPACE} -L airbyte -l airbyte=worker-pod --field-selector status.phase!=Running get pods
    }

    delete_worker_pod() {
      printf $1
      printf " "
      kubectl -n ${KUBE_NAMESPACE} delete pod "$1"
    }

    while :
    do
      (
          IFS=$'\n'
          for POD in `get_worker_pods`; do
              IFS=' '
              POD_NAME=`echo $POD | cut -d " " -f 1`
                  delete_worker_pod "$POD_NAME"
          done
      )
      sleep 3600
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-pod-sweeper
spec:
  replicas: 1
  selector:
    matchLabels:
      airbyte: pod-sweeper
  template:
    metadata:
      labels:
        airbyte: pod-sweeper
    spec:
      serviceAccountName: airbyte-admin
      containers:
        - name: airbyte-pod-sweeper
          image: bitnami/kubectl
          imagePullPolicy: IfNotPresent
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /script/sweep-pod.sh
              subPath: sweep-pod.sh
              name: sweep-pod-script
          command: ["/bin/bash", "-c", /script/sweep-pod.sh]
      volumes:
        - name: sweep-pod-script
          configMap:
            name: sweep-pod-script
            defaultMode: 0755
