apiVersion: v1
kind: Service
metadata:
  name: airbyte-server-svc
spec:
  type: ClusterIP
  ports:
  - name: server-svc
    protocol: TCP
    port: 8001
    targetPort: 8001
  selector:
    airbyte: server
