apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-temporal
spec:
  replicas: {{ .Values.temporal.replicas }}
  selector:
    matchLabels:
      airbyte: temporal
  template:
    metadata:
      labels:
        airbyte: temporal
    spec:
      containers:
        - name: airbyte-temporal
          image: "{{ .Values.temporal.image.repository }}:{{ .Values.temporal.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: DATABASE_USER
            - name: POSTGRES_PWD
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: DATABASE_PASSWORD
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: "config/dynamicconfig/development.yaml"
            - name: DB
              value: "postgresql"
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_SEEDS
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: POSTGRES_SEEDS
          ports:
            - containerPort: 7233
          volumeMounts:
            - name: airbyte-temporal-dynamicconfig
              mountPath: "/etc/temporal/config/dynamicconfig/"
      volumes:
        - name: airbyte-temporal-dynamicconfig
          configMap:
            name: airbyte-temporal-dynamicconfig
            items:
              - key: development.yaml
                path: development.yaml
