apiVersion: v1
kind: Service
metadata:
  name: airbyte-temporal-svc
spec:
  type: ClusterIP
  ports:
  - name: temporal-svc
    protocol: TCP
    port: 7233
    targetPort: 7233
  selector:
    airbyte: temporal
