apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-webapp
spec:
  replicas: {{ .Values.webapp.replicas }}
  selector:
    matchLabels:
      airbyte: webapp
  template:
    metadata:
      labels:
        airbyte: webapp
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: airbyte-webapp-container
          image: "{{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: AIRBYTE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: AIRBYTE_VERSION
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: API_URL
            - name: TRACKING_STRATEGY
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: TRACKING_STRATEGY
            - name: PAPERCUPS_STORYTIME
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: PAPERCUPS_STORYTIME
            - name: FULLSTORY
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: FULLSTORY
            - name: IS_DEMO
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: IS_DEMO
            - name: INTERNAL_API_HOST
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: INTERNAL_API_HOST
          ports:
            - containerPort: 80
