apiVersion: v1
kind: Service
metadata:
  name: airbyte-webapp-svc
spec:
  type: ClusterIP
  ports:
  - name: webapp-svc
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    airbyte: webapp
