apiVersion: v2
appVersion: 1.2.0
description: Helm chart to deploy airbyte
name: airbyte
type: application
version: "v1.0.0"
dependencies:
  - name: server
    version: "1.2.0"
    repository: "file://./charts/server"
  - name: temporal
    version: "1.2.0"
    repository: "file://./charts/temporal"
  - name: keycloak-setup
    version: "1.2.0"
    repository: "file://./charts/keycloak-setup"
  - name: metrics
    version: "1.2.0"
    repository: "file://./charts/metrics"
  - name: temporal-ui
    version: "1.2.0"
    repository: "file://./charts/temporal-ui"
  - name: worker
    version: "1.2.0"
    repository: "file://./charts/worker"
  - name: workload-api-server
    version: "1.2.0"
    repository: "file://./charts/workload-api-server"
  - name: common
    version: "1.2.0"
    repository: "file://./charts/common"
  - name: cron
    version: "1.2.0"
    repository: "file://./charts/cron"
  - name: connector-rollout-worker
    version: "1.2.0"
    repository: "file://./charts/connector-rollout-worker"
  - name: keycloak
    version: "1.2.0"
    repository: "file://./charts/keycloak"
  - name: webapp
    version: "1.2.0"
    repository: "file://./charts/webapp"
  - name: workload-launcher
    version: "1.2.0"
    repository: "file://./charts/workload-launcher"
  - name: airbyte-bootloader
    version: "1.2.0"
    repository: "file://./charts/airbyte-bootloader"
  - name: connector-builder-server
    version: "1.2.0"
    repository: "file://./charts/connector-builder-server"
  - name: pod-sweeper
    version: "1.2.0"
    repository: "file://./charts/pod-sweeper"
