{{- if and 
  (eq .Values.global.deploymentMode "oss") 
  (eq (lower (default "" .Values.global.storage.type)) "gcs") 
  (not .Values.global.storage.secretName)
  (not .Values.global.storage.storageSecretName)
}}
{{ $gcsConfig := required "You must set 'global.storage.gcs' when setting 'global.storage.type' to 'gcs'" .Values.global.storage.gcs }}
{{ $credentialsJson := required  "You must set 'global.storage.gcs.credentialsJson' when 'global.storage.secretName' is not set" .Values.global.storage.gcs.credentialsJson }}
apiVersion: v1
kind: Secret
metadata:
  name: gcs-log-creds-secret
  namespace: {{ .Release.Namespace }}
data:
  gcs-log-creds.json: {{ .Values.gcsLogCreds | b64enc | quote }}
{{- end }}
